### ISSUE TITLE
Gives wrong results when the code is run for some images in a loop

### ISSUE THREAD

**Issue by SurajSubramanian** [Layout-Parser/layout-parser#9]
The code works when it is run for a single image. But when I run the same code in a loop for few images from the publaynet dataset, cached results seem to apply (i.e. The bounding boxes overlap and the boxes for the previous images are also put in the current image).

**Comment by SurajSubramanian** [comment]
Code used : 
```
import layoutparser as lp # and other imports
model = lp.Detectron2LayoutModel('lp://PubLayNet/mask_rcnn_R_50_FPN_3x/config')

for img in os.listdir('images'):
    if '.jpg' not in img:
        continue
    input_ = cv2.imread(os.path.join(root, 'images', img))
    root = os.getcwd()
    layout = model.detect(input_)
    output = lp.draw_box(input_, layout)
    output = np.array(output)
    cv2.imwrite(os.path.join(root, 'output', img), output)
    with open(os.path.join(root, 'output-json', img.split('.')[0] + '.txt'), 'w') as f:
        f.write(str(layout))
```

**Comment by lolipopshock** [comment]
Thanks! It's fixed in v0.1.3: https://github.com/Layout-Parser/layout-parser/blob/dee2594cbabe2aa343cc81ea65f34f3a3b20d962/src/layoutparser/visualization.py#L107

**Comment by remidbs** [comment]
Hello! Thank you for your amazing work!
I ran into the same issue in version 0.1.3 and also with current master version of the code, so I think it is not resolved yet.
I fixed it by changing line `1488` of file `layoutparser/elements.py` from

```python
    def __init__(self, blocks: List = [], page_data: Dict = None):
        self._blocks = blocks
```
to
```python
    def __init__(self, blocks: Optional[List] = None, page_data: Dict = None):
        self._blocks = blocks if blocks is not None else []
```

See [here](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument) for reference.

**Comment by lolipopshock** [comment]
> Hello! Thank you for your amazing work!
> I ran into the same issue in version 0.1.3 and also with current master version of the code, so I think it is not resolved yet.
> I fixed it by changing line `1488` of file `layoutparser/elements.py` from
> 
> ```python
>     def __init__(self, blocks: List = [], page_data: Dict = None):
>         self._blocks = blocks
> ```
> 
> to
> 
> ```python
>     def __init__(self, blocks: Optional[List] = None, page_data: Dict = None):
>         self._blocks = blocks if blocks is not None else []
> ```
> 
> See [here](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument) for reference.

Thanks! Good catch and yeah, it's definitely incorrect to use `[]` as the default parameter value. Will fix this in the next release.
